// constants.js
export const doctorsData = [
    {
        id: 4,
        title: 'Dr. Kaur',
        location: 'Palo Alto, CA',
        profession: 'Primary Care Physician, MD',
        description: 'Doctor description here',
        image: require('./assets/doctor4.png'),
        officeImage: require('./assets/office2.jpg'),
        filters:['distance', 'mi5', 'gender', 'woman'],
        rating: 2,
        distance: '2',
        reviews: [
            { id: 1, name: 'John Doe', image: require('./assets/person1.jpg'), rating: 4, comment: 'Great doctor! I felt very welcomed and would definitely come back.' },
            { id: 2, name: 'Jane Smith', image: require('./assets/person2.jpg'), rating: 1, comment: 'Terrible service. I went in for a general check up and Dr. Kaur asked a lot of invansive questions.' },
            { id: 3, name: 'Alex Johnson', image: require('./assets/person3.jpg'), rating: 1, comment: 'Very bad service. I was judged for my pronouns and talked down to my entire appointment.' },
        ],
        phone: '(123) 456-7890',
        address: '123 Fantasy Drive Palo Alto, CA 94305'
    },
    {
        id: 1,
        title: 'Dr. Jayakar',
        location: 'Sunnyvale, CA',
        profession: 'Primary Care Physician, MD',
        description: 'Dr. Jayakar is an inclusive and LGBTQ+ friendly physician who welcomes patients from all walks of life with open arms. With a commitment to providing respectful and compassionate care to everyone, Dr. Jayakar creates a safe and affirming space for the LGBTQ+ community.',
        image: require('./assets/doctor1.png'),
        officeImage: require('./assets/office3.jpg'),
        filters:['distance', 'mi10', 'gender', 'woman', 'ratng', 'star4', 'star35', 'star3'],
        rating: 4,
        distance: '10',
        reviews: [
            { id: 1, name: 'Mateo', identities: 'gay man', image: require('./assets/person1.jpg'), rating: 4, comment: "It's reassuring to know that I can receive quality medical care in an inclusive and..." },
            { id: 2, name: 'Anonymous', identities: 'pansexual, nonbinary', image: require('./assets/empty-avatar.png'), rating: 3, comment: "My experience as a non-binary patient was generally satisfactory. The staff was..." },
            { id: 3, name: 'Anonymous', identities: 'lesbian', image: require('./assets/empty-avatar.png'), rating: 4, comment: "The staff was friendly, and I didn't face any discrimination based on my sexual..." },
            { id: 4, name: 'Anonymous', identities: 'gay', image: require('./assets/empty-avatar.png'), rating: 5, comment: "Dr. Jayakar was not only professional but also understanding of my specific needs..." },
            { id: 5, name: 'Ella', identities: 'lesbian woman', image: require('./assets/person2.jpg'), rating: 5, comment: 'Exceptional service! The doctor took the time to listen to my concerns and provided thorough explanations.' },
            { id: 6, name: 'Jordan', identities: 'bisexual', image: require('./assets/person3.jpg'), rating: 3, comment: 'Average experience. The waiting time was a bit long, but the doctor was knowledgeable and answered my questions.' },
            { id: 7, name: 'Anonymous', identities: 'ze/zir', image: require('./assets/empty-avatar.png'), rating: 4, comment: 'Great atmosphere! The clinic is clean, and the staff is friendly. I felt comfortable throughout my visit.' },
            { id: 8, name: 'Anonymous', identities: 'queer', image: require('./assets/empty-avatar.png'), rating: 2, comment: 'Disappointing visit. The doctor seemed rushed and didn\'t provide sufficient information. I expected better.' },
            { id: 9, name: 'Avery', identities: 'asexual, nonbinary', image: require('./assets/person4.jpg'), rating: 5, comment: 'Outstanding care! Dr. Jayakar is highly knowledgeable and attentive. The entire experience was exceptional, and I highly recommend this clinic.' },
        ],
        phone: '(559) 700-2313',
        address: '735 Mayfield Drive Palo Alto, CA 94305'
    },
    {
        id: 3,
        title: 'Dr. Posada',
        location: 'Redwood City, CA',
        profession: 'Primary Care Physician, MD',
        description: 'Primary Care Physician, MD',
        image: require('./assets/doctor3.png'),
        officeImage: require('./assets/office3.jpg'),
        filters:['distance', 'mi10', 'gender', 'man', 'ratng', 'star4', 'star35', 'star3'],
        rating: 4,
        distance: '8',
        reviews: [
            { id: 1, name: 'John Doe', image: require('./assets/person1.jpg'), rating: 4, comment: 'Great doctor!' },
            { id: 2, name: 'Jane Smith', image: require('./assets/person2.jpg'), rating: 5, comment: 'Excellent service.' },
            { id: 3, name: 'Alex Johnson', image: require('./assets/person3.jpg'), rating: 3, comment: 'Just okay.' },
        ],
    },
    {
        id: 2,
        title: 'Dr. Qureshi',
        location: 'San Francisco, CA',
        profession: 'Primary Care Physician, MD',
        description: 'Primary Care Physician, MD',
        image: require('./assets/doctor2.png'),
        officeImage: require('./assets/office1.jpg'),
        filters:['distance', 'mi25', 'gender', 'woman', 'ratng', 'star3'],
        rating: 3,
        distance: '35',
        reviews: [
            { id: 1, name: 'John Doe', image: require('./assets/person1.jpg'), rating: 4, comment: 'Great doctor!' },
            { id: 2, name: 'Jane Smith', image: require('./assets/person2.jpg'), rating: 5, comment: 'Excellent service.' },
            { id: 3, name: 'Alex Johnson', image: require('./assets/person3.jpg'), rating: 3, comment: 'Just okay.' },
        ],
    },
    
    {
        id: 6,
        title: 'Dr. Singh',
        location: 'Mountain View, CA',
        profession: 'Primary Care Physician, MD',
        description: 'Primary Care Physician, MD',
        image: require('./assets/doctor6.png'),
        officeImage: require('./assets/office2.jpg'),
        filters:['distance', 'mi10', 'gender', 'woman'],
        rating: 1,
        distance: '2',
        reviews: [
            { id: 1, name: 'John Doe', image: require('./assets/person1.jpg'), rating: 4, comment: 'Great doctor!' },
            { id: 2, name: 'Jane Smith', image: require('./assets/person2.jpg'), rating: 5, comment: 'Excellent service.' },
            { id: 3, name: 'Alex Johnson', image: require('./assets/person3.jpg'), rating: 3, comment: 'Just okay.' },
        ],
    },
    {
        id: 5,
        title: 'Dr. Suri',
        location: 'Cupertino, CA',
        profession: 'Primary Care Physician, MD',
        description: 'Primary Care Physician, MD',
        image: require('./assets/doctor5.png'),
        officeImage: require('./assets/office2.jpg'),
        filters:['distance', 'mi25', 'gender', 'man'],
        rating: 1,
        distance: '2',
        reviews: [
            { id: 1, name: 'John Doe', image: require('./assets/person1.jpg'), rating: 4, comment: 'Great doctor!' },
            { id: 2, name: 'Jane Smith', image: require('./assets/person2.jpg'), rating: 5, comment: 'Excellent service.' },
            { id: 3, name: 'Alex Johnson', image: require('./assets/person3.jpg'), rating: 3, comment: 'Just okay.' },
        ],
    },
    {
        id: 7,
        title: 'Dr. Rajput',
        location: 'Hayward, CA',
        profession: 'Primary Care Physician, MD',
        description: 'Primary Care Physician, MD',
        image: require('./assets/doctor7.png'),
        officeImage: require('./assets/office1.jpg'),
        filters:['distance', 'mi50', 'gender', 'woman', 'ratng', 'star4', 'star35', 'star3'],
        rating: 4,
        distance: '2',
        reviews: [
            { id: 1, name: 'John Doe', image: require('./assets/person1.jpg'), rating: 4, comment: 'Great doctor!' },
            { id: 2, name: 'Jane Smith', image: require('./assets/person2.jpg'), rating: 5, comment: 'Excellent service.' },
            { id: 3, name: 'Alex Johnson', image: require('./assets/person3.jpg'), rating: 3, comment: 'Just okay.' },
        ],
    },
    {
        id: 8,
        title: 'Dr. Smith',
        location: 'San Francisco, CA',
        profession: 'Cardiologist, MD',
        description: 'Cardiologist with expertise in heart health.',
        image: require('./assets/doctor1.png'),
        officeImage: require('./assets/office1.jpg'),
        filters: ['distance', 'mi10', 'gender', 'man'],
        rating: 4.5,
        distance: '5',
        reviews: [
          { id: 1, name: 'John Doe', image: require('./assets/person1.jpg'), rating: 4, comment: 'Great experience with Dr. Smith. Knowledgeable and friendly.' },
          { id: 2, name: 'Jane Smith', image: require('./assets/person2.jpg'), rating: 5, comment: 'Excellent cardiologist. Highly recommended.' },
          { id: 3, name: 'Alex Johnson', image: require('./assets/person3.jpg'), rating: 3, comment: 'Good service, but the waiting time was a bit long.' },
        ],
        phone: '(415) 123-4567',
        address: '456 Heartbeat Lane San Francisco, CA 94105',
      },
    //   {
	// 	title: "Dr. Blanchard",
	// 	phone: "1-396-651-5617",
	// 	address: "9881 Egestas Road",
	// 	rating: 0,
	// 	location: "College",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/settings",
	// 	officeImage: "/sub",
	// 	description: "tellus",
	// 	id: 92,
	// 	distance: 23
	// },
	// {
	// 	title: "Dr. Hughes",
	// 	phone: "(809) 451-8384",
	// 	address: "233-4731 Pellentesque St.",
	// 	rating: 4,
	// 	location: "Jackson",
	// 	profession: "Cardiologist, M.D.",
	// 	image: "/one",
	// 	officeImage: "/en-us",
	// 	description: "senectus",
	// 	id: 39,
	// 	distance: 79
	// },
	// {
	// 	title: "Dr. Thompson",
	// 	phone: "(890) 538-1969",
	// 	address: "Ap #239-5348 Luctus Street",
	// 	rating: 1,
	// 	location: "Birmingham",
	// 	profession: "Dermatologist, M.D.",
	// 	image: "/en-ca",
	// 	officeImage: "/user/110",
	// 	description: "ut",
	// 	id: 88,
	// 	distance: 25
	// },
	// {
	// 	title: "Dr. Ford",
	// 	phone: "(219) 423-4221",
	// 	address: "Ap #316-1389 Risus. St.",
	// 	rating: 1,
	// 	location: "Columbus",
	// 	profession: "Cardiologist, M.D.",
	// 	image: "/sub",
	// 	officeImage: "/one",
	// 	description: "nulla.",
	// 	id: 143,
	// 	distance: 79
	// },
	// {
	// 	title: "Dr. Cooley",
	// 	phone: "1-359-378-2476",
	// 	address: "Ap #244-1557 Lacus. Ave",
	// 	rating: 2,
	// 	location: "San Diego",
	// 	profession: "Dermatologist, M.D.",
	// 	image: "/en-ca",
	// 	officeImage: "/en-us",
	// 	description: "adipiscing",
	// 	id: 50,
	// 	distance: 50
	// },
	// {
	// 	title: "Dr. Payne",
	// 	phone: "(334) 187-2653",
	// 	address: "375-4237 Mauris St.",
	// 	rating: 3,
	// 	location: "Akron",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/settings",
	// 	officeImage: "/one",
	// 	description: "nec",
	// 	id: 82,
	// 	distance: 98
	// },
	// {
	// 	title: "Dr. Mills",
	// 	phone: "1-438-434-2276",
	// 	address: "P.O. Box 995, 6399 Dolor. Avenue",
	// 	rating: 3,
	// 	location: "Iowa City",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/site",
	// 	officeImage: "/group/9",
	// 	description: "elit",
	// 	id: 124,
	// 	distance: 41
	// },
	// {
	// 	title: "Dr. Kelley",
	// 	phone: "(828) 530-6037",
	// 	address: "Ap #824-3579 Est Road",
	// 	rating: 5,
	// 	location: "San Francisco",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/sub",
	// 	officeImage: "/en-ca",
	// 	description: "fringilla",
	// 	id: 113,
	// 	distance: 73
	// },
	// {
	// 	title: "Dr. Barnes",
	// 	phone: "1-784-852-9873",
	// 	address: "Ap #829-5479 Eget Av.",
	// 	rating: 3,
	// 	location: "Great Falls",
	// 	profession: "Dermatologist, M.D.",
	// 	image: "/one",
	// 	officeImage: "/user/110",
	// 	description: "tristique",
	// 	id: 118,
	// 	distance: 26
	// },
	// {
	// 	title: "Dr. Castillo",
	// 	phone: "1-307-281-6971",
	// 	address: "P.O. Box 838, 966 At Street",
	// 	rating: 5,
	// 	location: "Bear",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/fr",
	// 	officeImage: "/user/110",
	// 	description: "gravida",
	// 	id: 109,
	// 	distance: 24
	// },
	// {
	// 	title: "Dr. Myers",
	// 	phone: "1-704-885-5958",
	// 	address: "Ap #335-8963 Dignissim Rd.",
	// 	rating: 2,
	// 	location: "Colchester",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/one",
	// 	officeImage: "/settings",
	// 	description: "nec,",
	// 	id: 41,
	// 	distance: 52
	// },
	// {
	// 	title: "Dr. Bray",
	// 	phone: "(427) 379-8127",
	// 	address: "Ap #758-4873 Eros Av.",
	// 	rating: 3,
	// 	location: "Milwaukee",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/one",
	// 	officeImage: "/one",
	// 	description: "at,",
	// 	id: 149,
	// 	distance: 23
	// },
	// {
	// 	title: "Dr. Landry",
	// 	phone: "(333) 242-1345",
	// 	address: "P.O. Box 219, 3099 Gravida Avenue",
	// 	rating: 1,
	// 	location: "Grand Rapids",
	// 	profession: "Cardiologist, M.D.",
	// 	image: "/sub/cars",
	// 	officeImage: "/sub/cars",
	// 	description: "ipsum",
	// 	id: 149,
	// 	distance: 68
	// },
	// {
	// 	title: "Dr. Guerrero",
	// 	phone: "1-431-706-1438",
	// 	address: "711-511 Nulla. Rd.",
	// 	rating: 2,
	// 	location: "Nampa",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/en-ca",
	// 	officeImage: "/one",
	// 	description: "nec",
	// 	id: 50,
	// 	distance: 79
	// },
	// {
	// 	title: "Dr. Mills",
	// 	phone: "1-481-389-7515",
	// 	address: "Ap #860-6746 Amet, St.",
	// 	rating: 1,
	// 	location: "Indianapolis",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/settings",
	// 	officeImage: "/settings",
	// 	description: "enim.",
	// 	id: 95,
	// 	distance: 90
	// },
	// {
	// 	title: "Dr. Perry",
	// 	phone: "(461) 969-1512",
	// 	address: "150-3451 Placerat Street",
	// 	rating: 3,
	// 	location: "Lafayette",
	// 	profession: "Cardiologist, M.D.",
	// 	image: "/sub",
	// 	officeImage: "/en-ca",
	// 	description: "sed",
	// 	id: 73,
	// 	distance: 28
	// },
	// {
	// 	title: "Dr. Combs",
	// 	phone: "1-258-256-1568",
	// 	address: "Ap #415-771 Class Street",
	// 	rating: 4,
	// 	location: "Gresham",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/one",
	// 	officeImage: "/user/110",
	// 	description: "accumsan",
	// 	id: 120,
	// 	distance: 44
	// },
	// {
	// 	title: "Dr. Castillo",
	// 	phone: "1-823-789-6942",
	// 	address: "Ap #357-4752 Lorem Ave",
	// 	rating: 4,
	// 	location: "Fayetteville",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/settings",
	// 	officeImage: "/sub/cars",
	// 	description: "molestie",
	// 	id: 74,
	// 	distance: 59
	// },
	// {
	// 	title: "Dr. Prince",
	// 	phone: "(526) 233-4525",
	// 	address: "Ap #969-2961 Laoreet Av.",
	// 	rating: 3,
	// 	location: "Independence",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/site",
	// 	officeImage: "/one",
	// 	description: "justo.",
	// 	id: 122,
	// 	distance: 33
	// },
	// {
	// 	title: "Dr. Sargent",
	// 	phone: "(741) 417-4338",
	// 	address: "Ap #873-2950 Nulla. Rd.",
	// 	rating: 2,
	// 	location: "South Portland",
	// 	profession: "Cardiologist, M.D.",
	// 	image: "/settings",
	// 	officeImage: "/sub/cars",
	// 	description: "convallis",
	// 	id: 143,
	// 	distance: 81
	// },
	// {
	// 	title: "Dr. Austin",
	// 	phone: "(430) 808-5110",
	// 	address: "Ap #841-6876 Nec St.",
	// 	rating: 2,
	// 	location: "Bloomington",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/user/110",
	// 	officeImage: "/en-ca",
	// 	description: "rhoncus.",
	// 	id: 63,
	// 	distance: 76
	// },
	// {
	// 	title: "Dr. Alford",
	// 	phone: "1-779-915-6967",
	// 	address: "348-4238 Eget, Road",
	// 	rating: 4,
	// 	location: "Bloomington",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/user/110",
	// 	officeImage: "/site",
	// 	description: "tortor",
	// 	id: 136,
	// 	distance: 14
	// },
	// {
	// 	title: "Dr. Castillo",
	// 	phone: "1-688-270-4223",
	// 	address: "Ap #787-5185 Felis St.",
	// 	rating: 0,
	// 	location: "Gresham",
	// 	profession: "Dermatologist, M.D.",
	// 	image: "/en-ca",
	// 	officeImage: "/sub/cars",
	// 	description: "Fusce",
	// 	id: 140,
	// 	distance: 69
	// },
	// {
	// 	title: "Dr. Gaines",
	// 	phone: "(589) 176-0189",
	// 	address: "Ap #243-1512 Molestie. Ave",
	// 	rating: 2,
	// 	location: "Burlington",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/fr",
	// 	officeImage: "/user/110",
	// 	description: "at",
	// 	id: 73,
	// 	distance: 23
	// },
	// {
	// 	title: "Dr. Marsh",
	// 	phone: "1-190-175-0877",
	// 	address: "Ap #250-7125 Sagittis St.",
	// 	rating: 4,
	// 	location: "Columbia",
	// 	profession: "Gynecologist, M.D.",
	// 	image: "/sub",
	// 	officeImage: "/site",
	// 	description: "adipiscing.",
	// 	id: 86,
	// 	distance: 33
	// },
	// {
	// 	title: "Dr. Martin",
	// 	phone: "(350) 739-5849",
	// 	address: "230-1408 Morbi Av.",
	// 	rating: 4,
	// 	location: "Kailua",
	// 	profession: "Dermatologist, M.D.",
	// 	image: "/group/9",
	// 	officeImage: "/sub",
	// 	description: "Phasellus",
	// 	id: 24,
	// 	distance: 40
	// },
	// {
	// 	title: "Dr. James",
	// 	phone: "1-785-457-5051",
	// 	address: "Ap #867-959 Nullam Ave",
	// 	rating: 4,
	// 	location: "Fort Wayne",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/user/110",
	// 	officeImage: "/settings",
	// 	description: "tincidunt",
	// 	id: 114,
	// 	distance: 5
	// },
	// {
	// 	title: "Dr. Winters",
	// 	phone: "(588) 626-3120",
	// 	address: "861-6997 Erat Street",
	// 	rating: 2,
	// 	location: "Evansville",
	// 	profession: "Dermatologist, M.D.",
	// 	image: "/sub",
	// 	officeImage: "/user/110",
	// 	description: "in,",
	// 	id: 39,
	// 	distance: 38
	// },
	// {
	// 	title: "Dr. Stanley",
	// 	phone: "(677) 531-4117",
	// 	address: "Ap #668-7069 Laoreet Rd.",
	// 	rating: 0,
	// 	location: "Saint Louis",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/sub",
	// 	officeImage: "/en-ca",
	// 	description: "Curabitur",
	// 	id: 31,
	// 	distance: 23
	// },
	// {
	// 	title: "Dr. Scott",
	// 	phone: "1-559-949-1650",
	// 	address: "887-3323 Donec Rd.",
	// 	rating: 4,
	// 	location: "Fort Collins",
	// 	profession: "Orthopedic Surgeon, M.D.",
	// 	image: "/en-ca",
	// 	officeImage: "/group/9",
	// 	description: "ultricies",
	// 	id: 97,
	// 	distance: 27
	// }
  ];
  